version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /srv/docker/appdata/nextcloud:/config
      - /srv/docker/nextcloud:/data
    ports:
      - 443:443
    restart: unless-stopped
