version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=ENTER_PASSWORD #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=ENTER_PASSWORD #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=HOSTNAME #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /srv/docker/appdata/vscode/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped