version: '3.8'
services:
  mariadb:
    image: linuxserver/mariadb:latest
    ports:
      - 3306:3306
    environment:
      PUID: '1000'
      PGID: '1000'
      MYSQL_ROOT_PASSWORD: 'ENTER_PASSWORD'
      MYSQL_DATABASE: 'DATABASE'
      MYSQL_USER: 'USER'
      MYSQL_PASSWORD: 'ENTER_PASSWORD'
      TZ: America/Los_Angeles
    volumes:
      - /srv/docker/appdata/mariadb:/var/lib/mysql